import { Button, VerticalBox } from "std-widgets.slint";
import { WaveformVisualizer, WaveformVisualizerState } from "./wave-form.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    in property<string> drawCommands;
    out property <WaveformVisualizerState> waveformState: waveform.waveformState;


    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
     }

    waveform := WaveformVisualizer {
        width: parent.width;
        height: parent.height * 0.5;
        y: parent.height * 0.1;
        drawCommands: drawCommands;
    }

}